### PR TITLE
first time adding new files

### PR DESCRIPTION
**Pull request by ec49ce**
folder **OpenVPN** contains file clnt01.ovpn - created as home work for **lesson 7** 
folder **git-man** contains files and READ for minimal INIT git on windows 10 

edit:
vagrant files from previous lessons will be added at the weekend

### CODE REVIEW

**Review by drempost — COMMENTED** [review]
выглядит все прямо ок, только не совсем понимаю, как .bashrc будет работать на винде, там ведь линуксовые команды chmod и sed утилита, с echo и ps еще соглашусь, в Powershell работает. 
Конфиг для ssh тоже хорошо, git берет специализированный ключ, не обязательно стандартное имя id_rsa
bash_rc файл работает на windows 10?

**Comment by ec49ce** [comment]
> bashrc

i was looking for decision how to push to github with differents <key> in config file - and found this link. https://gist.github.com/jherax/979d052ad5759845028e6742d4e2343b
it had worked, so i decide leave files  .bash_profile and .bashrc .

**Comment by drempost** [comment]
Got it, if you tested it and it worked, well done! But in future, please wait for my approve PR before merge in the master branch.

**Comment by ec49ce** [comment]
Clearly. I made self approved, because at last lesson you had sayed than you had see our pull request and that pull request which you didn't approved  - we can close pull request by self. Next time I will wait for your closing pull request.

**Pull request merged**
